name: Java CI with Maven

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Maven Package
        run: mvn -B clean package -DskipTests
        working-directory: ./urlShortener

      - name: Maven Verify
        run: mvn -B verify
        working-directory: ./urlShortener
